//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/RightHand.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RightHand: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RightHand()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RightHand"",
    ""maps"": [
        {
            ""name"": ""PrimaryButton"",
            ""id"": ""400022f2-2e68-4eb0-9341-845f17fcbb77"",
            ""actions"": [
                {
                    ""name"": ""Press"",
                    ""type"": ""Button"",
                    ""id"": ""dc7450f6-6ea9-450d-8de1-da03577f9949"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0f12f55f-b4c0-4002-8d18-b5e409a7ee55"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PrimaryButton
        m_PrimaryButton = asset.FindActionMap("PrimaryButton", throwIfNotFound: true);
        m_PrimaryButton_Press = m_PrimaryButton.FindAction("Press", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PrimaryButton
    private readonly InputActionMap m_PrimaryButton;
    private List<IPrimaryButtonActions> m_PrimaryButtonActionsCallbackInterfaces = new List<IPrimaryButtonActions>();
    private readonly InputAction m_PrimaryButton_Press;
    public struct PrimaryButtonActions
    {
        private @RightHand m_Wrapper;
        public PrimaryButtonActions(@RightHand wrapper) { m_Wrapper = wrapper; }
        public InputAction @Press => m_Wrapper.m_PrimaryButton_Press;
        public InputActionMap Get() { return m_Wrapper.m_PrimaryButton; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PrimaryButtonActions set) { return set.Get(); }
        public void AddCallbacks(IPrimaryButtonActions instance)
        {
            if (instance == null || m_Wrapper.m_PrimaryButtonActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PrimaryButtonActionsCallbackInterfaces.Add(instance);
            @Press.started += instance.OnPress;
            @Press.performed += instance.OnPress;
            @Press.canceled += instance.OnPress;
        }

        private void UnregisterCallbacks(IPrimaryButtonActions instance)
        {
            @Press.started -= instance.OnPress;
            @Press.performed -= instance.OnPress;
            @Press.canceled -= instance.OnPress;
        }

        public void RemoveCallbacks(IPrimaryButtonActions instance)
        {
            if (m_Wrapper.m_PrimaryButtonActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPrimaryButtonActions instance)
        {
            foreach (var item in m_Wrapper.m_PrimaryButtonActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PrimaryButtonActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PrimaryButtonActions @PrimaryButton => new PrimaryButtonActions(this);
    public interface IPrimaryButtonActions
    {
        void OnPress(InputAction.CallbackContext context);
    }
}
